**1. Importação de bibliotecas e carregamento do arquivo no Google Colab:**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 2017.csv to 2017.csv


In [ ]:
df = pd.read_csv('2017.csv')

**2. Análise inicial de dados**

In [ ]:
df.head()

Year  Month  Day  Hour  Minute  Temperature  Clearsky DHI  Clearsky DNI  \
0  2017      1    1     0       0         -0.6             0             0   
1  2017      1    1     0      15         -0.6             0             0   
2  2017      1    1     0      30         -0.6             0             0   
3  2017      1    1     0      45         -0.6             0             0   
4  2017      1    1     1       0         -0.7             0             0   

   Clearsky GHI  Dew Point  DHI  DNI  GHI  Relative Humidity  \
0             0       -2.6    0    0    0              86.29   
1             0       -2.6    0    0    0              86.29   
2             0       -2.6    0    0    0              86.29   
3             0       -2.7    0    0    0              85.54   
4             0       -2.7    0    0    0              86.17   

   Solar Zenith Angle  Surface Albedo  Pressure  Wind Speed  Unnamed: 18  
0              152.92            0.12      1003         1.7          NaN  
1              150.22            0.12      1003         1.7          NaN  
2              147.43            0.12      1003         1.7          NaN  
3              144.60            0.12      1003         1.6          NaN  
4              141.71            0.12      1003         1.6          NaN

In [ ]:
df.shape

(35040, 19)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Year                35040 non-null  int64  
 1   Month               35040 non-null  int64  
 2   Day                 35040 non-null  int64  
 3   Hour                35040 non-null  int64  
 4   Minute              35040 non-null  int64  
 5   Temperature         35040 non-null  float64
 6   Clearsky DHI        35040 non-null  int64  
 7   Clearsky DNI        35040 non-null  int64  
 8   Clearsky GHI        35040 non-null  int64  
 9   Dew Point           35040 non-null  float64
 10  DHI                 35040 non-null  int64  
 11  DNI                 35040 non-null  int64  
 12  GHI                 35040 non-null  int64  
 13  Relative Humidity   35040 non-null  float64
 14  Solar Zenith Angle  35040 non-null  float64
 15  Surface Albedo      35040 non-null  float64
 16  Pres

In [ ]:
df.describe()

Year         Month           Day          Hour        Minute  \
count  35040.0  35040.000000  35040.000000  35040.000000  35040.000000   
mean    2017.0      6.526027     15.720548     11.500000     22.500000   
std        0.0      3.447901      8.796373      6.922285     16.770749   
min     2017.0      1.000000      1.000000      0.000000      0.000000   
25%     2017.0      4.000000      8.000000      5.750000     11.250000   
50%     2017.0      7.000000     16.000000     11.500000     22.500000   
75%     2017.0     10.000000     23.000000     17.250000     33.750000   
max     2017.0     12.000000     31.000000     23.000000     45.000000   

        Temperature  Clearsky DHI  Clearsky DNI  Clearsky GHI     Dew Point  \
count  35040.000000  35040.000000  35040.000000  35040.000000  35040.000000   
mean      17.598550     54.705251    316.586301    238.681079     10.000605   
std        8.713459     67.206394    359.823802    312.994277      5.086833   
min       -4.000000      0.000000      0.000000      0.000000     -5.300000   
25%       11.300000      0.000000      0.000000      0.000000      7.200000   
50%       16.800000      0.000000      0.000000      0.000000     10.500000   
75%       23.800000    105.000000    705.000000    475.000000     13.800000   
max       41.400000    415.000000    990.000000   1026.000000     21.900000   

                DHI           DNI           GHI  Relative Humidity  \
count  35040.000000  35040.000000  35040.000000       35040.000000   
mean      59.325342    234.925400    201.060674          65.853913   
std       86.020009    337.229851    294.243230          21.195051   
min        0.000000      0.000000      0.000000          14.960000   
25%        0.000000      0.000000      0.000000          50.037500   
50%        0.000000      0.000000      0.000000          68.120000   
75%      103.000000    530.000000    371.000000          84.370000   
max      488.000000    990.000000   1026.000000         100.000000   

       Solar Zenith Angle  Surface Albedo      Pressure    Wind Speed  \
count        35040.000000    35040.000000  35040.000000  35040.000000   
mean            89.672410        0.138274    993.971090      2.811116   
std             37.114298        0.012801      5.422638      1.439266   
min             14.620000        0.120000    977.000000      0.200000   
25%             60.350000        0.130000    990.000000      1.700000   
50%             89.300000        0.140000    993.000000      2.500000   
75%            119.130000        0.150000    998.000000      3.700000   
max            165.340000        0.160000   1010.000000     11.300000   

       Unnamed: 18  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN

**3. Limpeza dos dados (Data cleaning) 🧹**

In [ ]:
df.isnull().sum()

Year                      0
Month                     0
Day                       0
Hour                      0
Minute                    0
Temperature               0
Clearsky DHI              0
Clearsky DNI              0
Clearsky GHI              0
Dew Point                 0
DHI                       0
DNI                       0
GHI                       0
Relative Humidity         0
Solar Zenith Angle        0
Surface Albedo            0
Pressure                  0
Wind Speed                0
Unnamed: 18           35040
dtype: int64

In [ ]:
df.drop(columns=['Unnamed: 18'], inplace=True)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Temperature, Clearsky DHI, Clearsky DNI, Clearsky GHI, Dew Point, DHI, DNI, GHI, Relative Humidity, Solar Zenith Angle, Surface Albedo, Pressure, Wind Speed]
Index: []

In [ ]:
for col in df.columns:
    duplicados = df[col].duplicated().sum()
    print(f"Coluna '{col}' tem {duplicados} valores duplicados.")

Coluna 'Year' tem 35039 valores duplicados.
Coluna 'Month' tem 35028 valores duplicados.
Coluna 'Day' tem 35009 valores duplicados.
Coluna 'Hour' tem 35016 valores duplicados.
Coluna 'Minute' tem 35036 valores duplicados.
Coluna 'Temperature' tem 34587 valores duplicados.
Coluna 'Clearsky DHI' tem 34686 valores duplicados.
Coluna 'Clearsky DNI' tem 34052 valores duplicados.
Coluna 'Clearsky GHI' tem 34018 valores duplicados.
Coluna 'Dew Point' tem 34773 valores duplicados.
Coluna 'DHI' tem 34561 valores duplicados.
Coluna 'DNI' tem 34052 valores duplicados.
Coluna 'GHI' tem 34018 valores duplicados.
Coluna 'Relative Humidity' tem 27309 valores duplicados.
Coluna 'Solar Zenith Angle' tem 22021 valores duplicados.
Coluna 'Surface Albedo' tem 35035 valores duplicados.
Coluna 'Pressure' tem 35006 valores duplicados.
Coluna 'Wind Speed' tem 34933 valores duplicados.


In [ ]:
for col in df.columns:
    valores_duplicados = df[col][df[col].duplicated()]
    print(f"\nColuna '{col}':")
    print(valores_duplicados.unique())


Coluna 'Year':
[2017]

Coluna 'Month':
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Coluna 'Day':
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]

Coluna 'Hour':
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Coluna 'Minute':
[ 0 15 30 45]

Coluna 'Temperature':
[-0.6 -0.7 -0.8 -0.9 -1.  -1.1 -1.2  7.3  7.   6.7  4.3  3.   2.6  2.5
  2.2  2.   1.8  1.7  1.5  1.3  1.2  1.   0.9  0.8  0.7  0.5  0.4  0.3
  0.2  0.1  0.  -0.1 -0.2  3.6  5.5  5.9  6.8  7.2  8.2  8.   7.9  7.7
  7.5  6.5  6.1  5.7  5.2  4.9  4.7  4.   3.8  3.4  2.9  2.7  2.3  2.1
  1.9  2.8  3.3  7.1 11.5 11.2 10.7  9.9  9.4  6.9  6.6  6.3  6.2  6.
  5.6  5.4  5.3  5.1  5.   4.8  8.9 10.5 10.9 11.4 11.7 11.8 11.6 11.1
 10.4  9.2  9.5  9.6  9.7  9.8 10.  10.1 10.3 10.8 11.  12.4 12.5 12.6
 12.7 13.  14.5 14.6 14.7 14.4 14.2 14.  13.6 13.3 13.2 12.8 12.9 13.1
 13.5 13.8 14.1 14.3 13.9 13.7 12.3 12.  10.6  8.4  7.6  6.4  4.4  4.1
  3.1  1.1  0.6 -3.2 -3.3 -3

In [ ]:
df.dtypes

Year                    int64
Month                   int64
Day                     int64
Hour                    int64
Minute                  int64
Temperature           float64
Clearsky DHI            int64
Clearsky DNI            int64
Clearsky GHI            int64
Dew Point             float64
DHI                     int64
DNI                     int64
GHI                     int64
Relative Humidity     float64
Solar Zenith Angle    float64
Surface Albedo        float64
Pressure                int64
Wind Speed            float64
dtype: object

In [ ]:
df['time'] = pd.to_datetime(df[['Year', 'Month', 'Day', 'Hour', 'Minute']])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Year                35040 non-null  int64         
 1   Month               35040 non-null  int64         
 2   Day                 35040 non-null  int64         
 3   Hour                35040 non-null  int64         
 4   Minute              35040 non-null  int64         
 5   Temperature         35040 non-null  float64       
 6   Clearsky DHI        35040 non-null  int64         
 7   Clearsky DNI        35040 non-null  int64         
 8   Clearsky GHI        35040 non-null  int64         
 9   Dew Point           35040 non-null  float64       
 10  DHI                 35040 non-null  int64         
 11  DNI                 35040 non-null  int64         
 12  GHI                 35040 non-null  int64         
 13  Relative Humidity   35040 non-null  float64   

In [ ]:
def get_season_north(date):
    day = date.day
    month = date.month

    if (month == 12 and day >= 21) or (1 <= month <= 2) or (month == 3 and day < 20):
        return 'Winter'
    elif (month == 3 and day >= 20) or (4 <= month <= 5) or (month == 6 and day < 21):
        return 'Spring'
    elif (month == 6 and day >= 21) or (7 <= month <= 8) or (month == 9 and day < 22):
        return 'Summer'
    elif (month == 9 and day >= 22) or (10 <= month <= 11) or (month == 12 and day < 21):
        return 'Autumn'


In [ ]:
df['season'] = df['time'].apply(get_season_north)
